case: include DateDuration and sort includes
When trying to do something like:

```
Arel.when(some_cond).then(some_date).format('%Y-%m-%d')
```

We'd get an error message that looks like this:

```
NoMethodError: private method `format' called for #<ArelExtensions::Nodes::Case:…
```

Which is obviously an oversight.

Case nodes should support date/datetime `format`.