case: fix inheritance for Arel versions >= 10
The version comparison was being done on a string, and lexical sorting if 7 is after 1,
thus resulting in not inheriting from Arel::Nodes::Case, and then we get
errors like:

    NoMethodError: undefined method `eq' for #<ArelExtensions::Nodes::Case:0x00005578f1ac1a10>

Fix that by using the Gem::Version class.

Fixes #28