v2.1.6/1.3.6
    functions: add if_present

    mysql: better infer types of Format nodes

    news: new

    readme: document blank, not_blank, present, and coalesce_blank

    functions: add coalesce_blank

    case: include DateDuration and sort includes

    When trying to do something like:

    ```
    Arel.when(some_cond).then(some_date).format('%Y-%m-%d')
    ```

    We'd get an error message that looks like this:

    ```
    NoMethodError: private method `format' called for #<ArelExtensions::Nodes::Case:…
    ```

    Which is obviously an oversight.

    Case nodes should support date/datetime `format`.

    string: make present an alias to not_blank

    fix some old compatibility issue with rails 4.2 calculation module

    mssql: quote: monkeypatch for JRuby + AR < 5

    The patch was taken from AR 6 code.

    activerecord-jdbc relied on code burried deep in the connection adapter
    to handle quoting.

    It mainly depended on the column type to decide on the quoting strategy.

    This patch denies any such dependencies and relies on the value type only.

    mysql: support rails < 5.2

    postgres: add rollup patch for rails < 5.2

    gemfiles: rename for consistency

    gemspecs: remove rdoc dependency

    It's making a lot of trouble, and we can do without it.

    ci: get rid of unnecessary build step

    ci: add --no-document to speed up updates

    rollup: add at[:col].rollup shorthand

    rollup: add Arel.rollup shorthand

    mysql: support arbitrary rollup in group

    visitors: add support for rollup
    This patch also adds it to mssql and oracle.

    doc: update the abstract