oracle: require base64
Fixes:
```
Error:
ArelExtensions::WithAr::ListTest#test_alias_shortened:
NameError: uninitialized constant Arel::Base64
    Base64.urlsafe_encode64(Digest::MD5.new.digest(s)).tr('=', '').tr('-', '_')
    ^^^^^^
    /home/runner/work/arel-extensions/arel-extensions/lib/arel_extensions.rb:144:in `shorten'
    /home/runner/work/arel-extensions/arel-extensions/test/with_ar/all_agnostic_test.rb:919:in `test_alias_shortened'
rails test home/runner/work/arel-extensions/arel-extensions/test/with_ar/all_agnostic_test.rb:917
```